#ifndef _ARM_CONTROL_H__
#define _ARM_CONTROL_H__

#include "stdint.h"

#include "arm_task.h"

#define ARM_RC_DEADLINE (2)

#define JOINT_1_CONTROL_SEN (0.0002f)
#define JOINT_2_CONTROL_SEN (0.04f)
#define JOINT_3_CONTROL_SEN (0.04f)
#define JOINT_4_CONTROL_SEN (0.04f)
#define JOINT_5_CONTROL_SEN (0.04f)
#define JOINT_6_CONTROL_SEN (0.04f)

#define POSE_X_CONTROL_SEN (0.001f)
#define POSE_Y_CONTROL_SEN (0.001f)
#define POSE_Z_CONTROL_SEN (0.001f)
#define POSE_AY_CONTROL_SEN (0.005f)
#define POSE_AP_CONTROL_SEN (0.005f)
#define POSE_AR_CONTROL_SEN (0.005f)

#define SILVER_MINING_X_CONTROL_SEN (0.0002f)
#define SILVER_MINING_Y_CONTROL_SEN (0.0002f)
#define SILVER_MINING_Z_CONTROL_SEN (0.0002f)
#define SILVER_MINING_AY_CONTROL_SEN (0.0006f)
#define SILVER_MINING_AP_CONTROL_SEN (0.0006f)
#define SILVER_MINING_AR_CONTROL_SEN (0.0006f)

#define JOINT_1_HOMING_STEP_ANGLE (0.01f)
#define JOINT_1_HOMING_TORQUE_THRESHOLD (2.0f)
#define JOINT_1_HOMING_ANGLE (-13.021768f)

#define JOINT_2_START_ANGLE (0.0f)

#define JOINT_3_START_ANGLE (0.0f)

#define JOINT_4_HOMING_STEP_ANGLE (0.005f)
#define JOINT_4_HOMING_TORQUE_THRESHOLD (1.0f)
#define JOINT_4_HOMING_ANGLE (-124.480934f)
#define JOINT_4_START_ANGLE (0.0f)

#define JOINT_5_HOMING_STEP_ANGLE (0.005f)
#define JOINT_5_HOMING_TORQUE_THRESHOLD (5.0f)
#define JOINT_5_HOMING_ANGLE (-85.0f)
#define JOINT_5_START_ANGLE (0.0f)

#define JOINT_6_START_ANGLE (0.0f)

#define SILVER_MINING_STEP_INIT (0)
#define SILVER_MINING_STEP_READY (1)
#define SILVER_MINING_STEP_GRAB (2)
#define SILVER_MINING_STEP_WAIT (3)
#define SILVER_MINING_STEP_OK (4)

#define STORAGE_PUSH_STEP_INIT (0)
#define STORAGE_PUSH_STEP_START (1)
#define STORAGE_PUSH_STEP_SLOT (2)
#define STORAGE_PUSH_STEP_PUSH_IN (3)

#define STORAGE_POP_STEP_INIT (0)

/**
 * @brief 根据机械臂控制模式 配置电机控制模式 更新机械臂控制量
 */
extern void arm_mode_control(engineer_scara_arm_s *scara_arm);

#endif /* _ARM_CONTROL_H__ */
