#include "pinmux.h"

void init_spi_pins(SPI_Type *ptr) {
  if (ptr == HPM_SPI0) {
    // HPM_IOC->PAD[SPI0_CSN].FUNC_CTL = IOC_PD22_FUNC_CTL_SPI0_CSN;
    HPM_IOC->PAD[SPI0_MISO].FUNC_CTL = IOC_PD26_FUNC_CTL_SPI0_MISO;
    HPM_IOC->PAD[SPI0_MOSI].FUNC_CTL = IOC_PD21_FUNC_CTL_SPI0_MOSI;
    // HPM_IOC->PAD[SPI0_SCLK].FUNC_CTL = IOC_PD27_FUNC_CTL_SPI0_SCLK;
    HPM_IOC->PAD[SPI0_SCLK].FUNC_CTL = IOC_PD27_FUNC_CTL_SPI0_SCLK | IOC_PAD_FUNC_CTL_LOOP_BACK_SET(1);
  } else if (ptr == HPM_SPI1) {
    // HPM_IOC->PAD[SPI1_CSN].FUNC_CTL = IOC_PE03_FUNC_CTL_SPI1_CSN;
    HPM_IOC->PAD[SPI1_MISO].FUNC_CTL = IOC_PD30_FUNC_CTL_SPI1_MISO;
    HPM_IOC->PAD[SPI1_MOSI].FUNC_CTL = IOC_PE04_FUNC_CTL_SPI1_MOSI;
    HPM_IOC->PAD[SPI1_SCLK].FUNC_CTL = IOC_PD31_FUNC_CTL_SPI1_SCLK | IOC_PAD_FUNC_CTL_LOOP_BACK_SET(1);
  } else {
    while (1) {
    }
  }
}

void init_pwm_pins(PWM_Type *ptr) {
  if (ptr == HPM_PWM0) {
    HPM_IOC->PAD[PWM0_CH1].FUNC_CTL = IOC_PC01_FUNC_CTL_PWM0_P_0;
    HPM_IOC->PAD[PWM0_CH2].FUNC_CTL = IOC_PC00_FUNC_CTL_PWM0_P_1;
    HPM_IOC->PAD[PWM0_CH3].FUNC_CTL = IOC_PB31_FUNC_CTL_PWM0_P_2;
    HPM_IOC->PAD[PWM0_CH4].FUNC_CTL = IOC_PA31_FUNC_CTL_PWM0_P_3;
  } else {
    while (1) {
    }
  }
}

void init_usb_pins(USB_Type *ptr) {
  if (ptr == HPM_USB0) {
    /* USB0 ID */
    HPM_IOC->PAD[USB0_ID].FUNC_CTL = IOC_PF10_FUNC_CTL_USB0_ID;
    HPM_IOC->PAD[USB0_ID].PAD_CTL = IOC_PAD_PAD_CTL_PS_SET(1) | IOC_PAD_PAD_CTL_PE_SET(1);
    // HPM_IOC->PAD[IOC_PAD_PF10].FUNC_CTL = IOC_PF10_FUNC_CTL_GPIO_F_10;
    // HPM_IOC->PAD[IOC_PAD_PF10].PAD_CTL = IOC_PAD_PAD_CTL_PS_SET(1) | IOC_PAD_PAD_CTL_PE_SET(1);

    /* USB0 OC */
    HPM_IOC->PAD[USB0_OC].FUNC_CTL = IOC_PE29_FUNC_CTL_USB0_OC;
    HPM_IOC->PAD[USB0_OC].PAD_CTL = IOC_PAD_PAD_CTL_PS_SET(1) | IOC_PAD_PAD_CTL_PE_SET(1);
    // HPM_IOC->PAD[IOC_PAD_PF08].FUNC_CTL = IOC_PF08_FUNC_CTL_GPIO_F_08;
    // HPM_IOC->PAD[IOC_PAD_PF08].PAD_CTL = IOC_PAD_PAD_CTL_PS_SET(1) | IOC_PAD_PAD_CTL_PE_SET(1);
    HPM_IOC->PAD[USB0_PWR].FUNC_CTL = IOC_PF09_FUNC_CTL_USB0_PWR;
  } else if (ptr == HPM_USB1) {
    HPM_IOC->PAD[USB1_ID].FUNC_CTL = IOC_PF07_FUNC_CTL_USB1_ID;
    HPM_IOC->PAD[USB1_ID].PAD_CTL = IOC_PAD_PAD_CTL_PS_SET(1) | IOC_PAD_PAD_CTL_PE_SET(1);
    HPM_IOC->PAD[USB1_OC].FUNC_CTL = IOC_PF05_FUNC_CTL_USB1_OC;
    HPM_IOC->PAD[USB1_OC].PAD_CTL = IOC_PAD_PAD_CTL_PS_SET(1) | IOC_PAD_PAD_CTL_PE_SET(1);
    HPM_IOC->PAD[USB1_PWR].FUNC_CTL = IOC_PF06_FUNC_CTL_USB1_PWR;
  } else {
    while (1) {
    }
  }
}

void init_can_pins(CAN_Type *ptr) {
  if (ptr == HPM_CAN0) {
    HPM_IOC->PAD[CAN0_TXD].FUNC_CTL = IOC_PB15_FUNC_CTL_CAN0_TXD;
    HPM_IOC->PAD[CAN0_RXD].FUNC_CTL = IOC_PB17_FUNC_CTL_CAN0_RXD;
  } else if (ptr == HPM_CAN1) {
    HPM_IOC->PAD[CAN1_TXD].FUNC_CTL = IOC_PB19_FUNC_CTL_CAN1_TXD;
    HPM_IOC->PAD[CAN1_RXD].FUNC_CTL = IOC_PB18_FUNC_CTL_CAN1_RXD;
  } else if (ptr == HPM_CAN2) {
    HPM_IOC->PAD[CAN2_TXD].FUNC_CTL = IOC_PB09_FUNC_CTL_CAN2_TXD;
    HPM_IOC->PAD[CAN2_RXD].FUNC_CTL = IOC_PB08_FUNC_CTL_CAN2_RXD;
  } else if (ptr == HPM_CAN3) {
    HPM_IOC->PAD[CAN3_RXD].FUNC_CTL = IOC_PA29_FUNC_CTL_CAN3_RXD;
    HPM_IOC->PAD[CAN3_TXD].FUNC_CTL = IOC_PA30_FUNC_CTL_CAN3_TXD;
  } else {
    while (1) {
    }
  }
}

void init_uart_pins(UART_Type *ptr) {
  if (ptr == HPM_UART0) {
    HPM_IOC->PAD[UART0_RX].FUNC_CTL = IOC_PB28_FUNC_CTL_UART0_RXD;
    HPM_IOC->PAD[UART0_TX].FUNC_CTL = IOC_PB23_FUNC_CTL_UART0_TXD;
  } else if (ptr == HPM_UART1) {
    HPM_IOC->PAD[UART1_RX].FUNC_CTL = IOC_PB26_FUNC_CTL_UART1_RXD;
    HPM_IOC->PAD[UART1_TX].FUNC_CTL = IOC_PB27_FUNC_CTL_UART1_TXD;
  } else if (ptr == HPM_UART2) {
    HPM_IOC->PAD[UART2_RX].FUNC_CTL = IOC_PB21_FUNC_CTL_UART2_RXD;
    HPM_IOC->PAD[UART2_TX].FUNC_CTL = IOC_PB22_FUNC_CTL_UART2_TXD;
  } else if (ptr == HPM_UART3) {
    HPM_IOC->PAD[UART3_RX].FUNC_CTL = IOC_PB24_FUNC_CTL_UART3_RXD;
    HPM_IOC->PAD[UART3_TX].FUNC_CTL = IOC_PB25_FUNC_CTL_UART3_TXD;
  } else if (ptr == HPM_UART4) {
    HPM_IOC->PAD[UART4_RX].FUNC_CTL = IOC_PB29_FUNC_CTL_UART4_RXD;
    HPM_IOC->PAD[UART4_TX].FUNC_CTL = IOC_PB30_FUNC_CTL_UART4_TXD;
  } else if (ptr == HPM_UART5) {
    HPM_IOC->PAD[UART5_RX].FUNC_CTL = IOC_PA07_FUNC_CTL_UART5_RXD;
    HPM_IOC->PAD[UART5_TX].FUNC_CTL = IOC_PA08_FUNC_CTL_UART5_TXD;
  } else {
    while (1) {
    }
  }
}

void init_i2c_pins(I2C_Type *ptr) {
  if (ptr == HPM_I2C0) {
    HPM_IOC->PAD[I2C0_SCL].FUNC_CTL = IOC_PA06_FUNC_CTL_I2C0_SCL | IOC_PAD_FUNC_CTL_LOOP_BACK_MASK;
    HPM_IOC->PAD[I2C0_SDA].FUNC_CTL = IOC_PA05_FUNC_CTL_I2C0_SDA | IOC_PAD_FUNC_CTL_LOOP_BACK_MASK;
    HPM_IOC->PAD[I2C0_SCL].PAD_CTL = IOC_PAD_PAD_CTL_OD_MASK;
    HPM_IOC->PAD[I2C0_SDA].PAD_CTL = IOC_PAD_PAD_CTL_OD_MASK;
  } else if (ptr == HPM_I2C1) {
    HPM_IOC->PAD[I2C1_SCL].FUNC_CTL = IOC_PA11_FUNC_CTL_I2C1_SCL | IOC_PAD_FUNC_CTL_LOOP_BACK_MASK;
    HPM_IOC->PAD[I2C1_SDA].FUNC_CTL = IOC_PA10_FUNC_CTL_I2C1_SDA | IOC_PAD_FUNC_CTL_LOOP_BACK_MASK;
    HPM_IOC->PAD[I2C1_SCL].PAD_CTL = IOC_PAD_PAD_CTL_OD_MASK;
    HPM_IOC->PAD[I2C1_SDA].PAD_CTL = IOC_PAD_PAD_CTL_OD_MASK;
  } else {
    while (1) {
    }
  }
}

void init_i2c_pins_as_gpio(I2C_Type *ptr) {
  if (ptr == HPM_I2C0) {
    HPM_IOC->PAD[I2C0_SCL].FUNC_CTL = IOC_PA06_FUNC_CTL_GPIO_A_06;
    HPM_IOC->PAD[I2C0_SDA].FUNC_CTL = IOC_PA05_FUNC_CTL_GPIO_A_05;
  } else if (ptr == HPM_I2C1) {
    HPM_IOC->PAD[I2C1_SCL].FUNC_CTL = IOC_PA11_FUNC_CTL_GPIO_A_11;
    HPM_IOC->PAD[I2C1_SDA].FUNC_CTL = IOC_PA10_FUNC_CTL_GPIO_A_10;
  } else {
    while (1) {
    }
  }
}

void init_led_pins_as_gpio(void) {
  HPM_IOC->PAD[RGB_R].FUNC_CTL = IOC_PA02_FUNC_CTL_GPIO_A_02;
  HPM_IOC->PAD[RGB_G].FUNC_CTL = IOC_PA03_FUNC_CTL_GPIO_A_03;
  HPM_IOC->PAD[RGB_B].FUNC_CTL = IOC_PA04_FUNC_CTL_GPIO_A_04;
}
